# Form implementation generated from reading ui file 'c:\Users\mekae\Desktop\Projects\ML Digit Recog\paintApp\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1282, 720)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("/*background:rgb(42, 42, 42)*/")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\mekae\\Desktop\\Projects\\ML Digit Recog\\paintApp\\icon.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.recognizeButton = QtWidgets.QPushButton(Form)
        self.recognizeButton.setEnabled(True)
        self.recognizeButton.setGeometry(QtCore.QRect(333, 597, 189, 48))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.recognizeButton.setFont(font)
        self.recognizeButton.setStyleSheet("font: 700 12pt \"Inter\";\n"
"letter-spacing: 3px;")
        self.recognizeButton.setObjectName("recognizeButton")
        self.digitResult = QtWidgets.QFrame(Form)
        self.digitResult.setGeometry(QtCore.QRect(853, 0, 427, 720))
        self.digitResult.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.digitResult.setStyleSheet("background: rgb(236, 236, 236)")
        self.digitResult.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.digitResult.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.digitResult.setObjectName("digitResult")
        self.clearButton = QtWidgets.QPushButton(Form)
        self.clearButton.setEnabled(True)
        self.clearButton.setGeometry(QtCore.QRect(385, 656, 83, 23))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("font: 700 8pt \"Inter\";\n"
"letter-spacing: 1.5px;")
        self.clearButton.setObjectName("clearButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(852, 336, 431, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(34)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 700 34pt \"Inter\";\n"
"letter-spacing: 6px;\n"
"color: rgb(50, 50, 50)\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(1240, 0, 40, 33))
        self.closeButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    image: url(:/resources/Close.png);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    image: url(:/resources/Close_hover.png);\n"
"}\n"
"\n"
"")
        self.closeButton.setText("")
        self.closeButton.setIconSize(QtCore.QSize(40, 33))
        self.closeButton.setAutoDefault(False)
        self.closeButton.setDefault(False)
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.resultView = QtWidgets.QLabel(Form)
        self.resultView.setGeometry(QtCore.QRect(972, 393, 189, 48))
        self.resultView.setStyleSheet("")
        self.resultView.setText("")
        self.resultView.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultView.setObjectName("resultView")
        self.maximizeButton = QtWidgets.QPushButton(Form)
        self.maximizeButton.setGeometry(QtCore.QRect(1200, 0, 40, 33))
        self.maximizeButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    image: url(:/resources/Maximize.png);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    image: url(:/resources/Maximize_hover.png);\n"
"}\n"
"\n"
"")
        self.maximizeButton.setText("")
        self.maximizeButton.setIconSize(QtCore.QSize(40, 33))
        self.maximizeButton.setAutoDefault(False)
        self.maximizeButton.setDefault(False)
        self.maximizeButton.setFlat(True)
        self.maximizeButton.setObjectName("maximizeButton")
        self.minimizeButton = QtWidgets.QPushButton(Form)
        self.minimizeButton.setGeometry(QtCore.QRect(1160, 0, 40, 33))
        self.minimizeButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    image: url(:/resources/Minimize.png);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    image: url(:/resources/Minimize_hover.png);\n"
"}\n"
"\n"
"")
        self.minimizeButton.setText("")
        self.minimizeButton.setIconSize(QtCore.QSize(40, 33))
        self.minimizeButton.setAutoDefault(False)
        self.minimizeButton.setDefault(False)
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        self.digitResult.raise_()
        self.recognizeButton.raise_()
        self.label.raise_()
        self.clearButton.raise_()
        self.label_2.raise_()
        self.closeButton.raise_()
        self.resultView.raise_()
        self.maximizeButton.raise_()
        self.minimizeButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Handwritten Digit Recognizer"))
        self.recognizeButton.setText(_translate("Form", "RECOGNIZE"))
        self.clearButton.setText(_translate("Form", "CLEAR"))
        self.label_2.setText(_translate("Form", "RESULT"))
